var globalSearchData = [
  { name: "Zou", map: "zoumap.html" },
  { name: "Wano", map: "wanomap.html" },
  { name: "Marineford", map: "marinefordmap.html" },
  { name: "Alabasta", map: "alabastamap.html" },
  { name: "Dressrosa", map: "dressrosamap.html" },
  { name: "Drum", map: "drum.html" },
  { name: "Egghead", map: "eggheadmap.html" },
  { name: "Enies Lobby", map: "enieslobbymap.html" },
  { name: "Fishman Island", map: "fishman-island.html" },
  { name: "Elbaph", map: "elbaph.html" },
  { name: "Impel Down", map: "impeldown.html" },
  { name: "Blueworld", map: "index.html" },
  { name: "Mary Geoise", map: "mary-geoise.html" },
  { name: "Onigashima", map: "onigashimamap.html" },
  { name: "Punk Hazard", map: "punkhazardmap.html" },
  { name: "Sabaody", map: "sabaodymap.html" },
  { name: "Skypea", map: "skypiea.html" },
  { name: "Space", map: "space.html" },
  { name: "Thriller Bark", map: "thrillerbark.html" },
  { name: "Whole Cake Island", map: "wcimap.html" },
  { name: "Water Seven", map: "water7map.html" },
  { name: "Uganda", map: "zou.html" },
];